remote_theme: saifkhichi96/simple-material

baseurl: https://saifkhichi96.github.io # homepage url
logo: /assets/images/logo.png # site logo

# page-specific customizations
title: Signature Extraction
categories: Machine Learning
cover: /simple-material/_site/assets/img/photo.png
icon: /simple-material/_site/assets/img/logo.png
